### PR TITLE
Converted to swift 2.0 syntax and successfully run in Xcode 7 beta 5, iOS 9 beta 5

### PR DESCRIPTION
**Pull request by theniceboy**

### CODE REVIEW

**Comment by bennichols** [comment]
Thanks! I've merged this under the Swift2.0 branch. If no one has any problems with it, I'll merge it into master.

**Comment by theniceboy** [comment]
:D

**Comment by theniceboy** [comment]
I don't know how to create a pull request that can create a new branch. Do you know how to to that? @bennichols

**Comment by bennichols** [comment]
@theniceboy I just created a new branch and merged it in manually.

**Pull request closed without merging**
